name: Generate GitHub README Terminal
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg -y
      - name: Install package
        run: pip install github-readme-terminal
      - name: Run script
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output.gif
          git commit -m "Update terminal gif" || exit 0
          git push
